QT += core network
CONFIG += staticlib
DEFINES -= QT3_SUPPORT
DEFINES += QT_STRICT_ITERATORS
INCLUDEPATH += ../
DEPENDPATH += ../
TARGET = qwwsmtpclient
TEMPLATE = lib
SOURCES += qwwsmtpclient.cpp
HEADERS += qwwsmtpclient.h
