if(NOT MAKENSIS)
    find_program(MAKENSIS makensis)
    if(NOT MAKENSIS)
        set(MakeNSIS_FOUND FALSE)
        message(STATUS "makensis not found")
    else()
        set(MakeNSIS_FOUND TRUE)
        message(STATUS "Found makensis: ${MAKENSIS}")
    endif()
    mark_as_advanced(MAKENSIS)
else()
    set(MakeNSIS_FOUND TRUE)
endif()
